[[entries]]
from = 2021
to = "present"
pos = "Algorithm Engineer and Operations Research Expert"
com = "MOIA"
loc = "Hamburg, Germany"

[[entries]]
from = 2020
to = 2020
pos = "Developer"
com = "AT&T"
loc = "Los Angeles, USA"

[[entries]]
from = 2018
to = "present"
pos = "Freelancer"
com = "Toptal"

[[entries]]
from = 2018
to = 2019
pos = "Lead developer"
com = "Chorefree"
loc = "Vancouver, Canada"

[[entries]]
from = 2010
to = 2017
pos = "Researcher"
com = "KU Leuven"
loc = "Belgium"

[[entries]]
from = 2008
to = 2010
pos = "MSc Computer Science"
com = "TU Delft"
loc = "The Netherlands"

[[entries]]
from = 2004
to = 2009
pos = "Software engineer"
com = "Floorplanner.com"
loc = "The Netherlands"

[[entries]]
from = 2004
to = 2008
pos = "BSc Computer Science"
com = "TU Delft"
loc = "The Netherlands"
